<?php
/**
 * SalesChannel
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ServeXS\Shopware\v6\Store\Model;

use \ArrayAccess;
use \ServeXS\Shopware\v6\Store\ObjectSerializer;

/**
 * SalesChannel Class Doc Comment
 *
 * @category Class
 * @description Added since version: 6.0.0.0
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SalesChannel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SalesChannel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'language_id' => 'string',
        'customer_group_id' => 'string',
        'currency_id' => 'string',
        'payment_method_id' => 'string',
        'shipping_method_id' => 'string',
        'country_id' => 'string',
        'navigation_category_id' => 'string',
        'navigation_category_version_id' => 'string',
        'navigation_category_depth' => 'int',
        'footer_category_id' => 'string',
        'footer_category_version_id' => 'string',
        'service_category_id' => 'string',
        'service_category_version_id' => 'string',
        'mail_header_footer_id' => 'string',
        'hreflang_default_domain_id' => 'string',
        'name' => 'string',
        'short_name' => 'string',
        'tax_calculation_type' => 'string',
        'configuration' => 'object',
        'active' => 'bool',
        'hreflang_active' => 'bool',
        'maintenance' => 'bool',
        'custom_fields' => 'object',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'translated' => 'object',
        'language' => '\ServeXS\Shopware\v6\Store\Model\Language',
        'currency' => '\ServeXS\Shopware\v6\Store\Model\Currency',
        'payment_method' => '\ServeXS\Shopware\v6\Store\Model\PaymentMethod',
        'shipping_method' => '\ServeXS\Shopware\v6\Store\Model\ShippingMethod',
        'country' => '\ServeXS\Shopware\v6\Store\Model\Country',
        'domains' => '\ServeXS\Shopware\v6\Store\Model\SalesChannelDomain',
        'navigation_category' => '\ServeXS\Shopware\v6\Store\Model\Category',
        'footer_category' => '\ServeXS\Shopware\v6\Store\Model\Category',
        'service_category' => '\ServeXS\Shopware\v6\Store\Model\Category',
        'hreflang_default_domain' => '\ServeXS\Shopware\v6\Store\Model\SalesChannelDomain'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'language_id' => null,
        'customer_group_id' => null,
        'currency_id' => null,
        'payment_method_id' => null,
        'shipping_method_id' => null,
        'country_id' => null,
        'navigation_category_id' => null,
        'navigation_category_version_id' => null,
        'navigation_category_depth' => 'int64',
        'footer_category_id' => null,
        'footer_category_version_id' => null,
        'service_category_id' => null,
        'service_category_version_id' => null,
        'mail_header_footer_id' => null,
        'hreflang_default_domain_id' => null,
        'name' => null,
        'short_name' => null,
        'tax_calculation_type' => null,
        'configuration' => null,
        'active' => null,
        'hreflang_active' => null,
        'maintenance' => null,
        'custom_fields' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'translated' => null,
        'language' => null,
        'currency' => null,
        'payment_method' => null,
        'shipping_method' => null,
        'country' => null,
        'domains' => null,
        'navigation_category' => null,
        'footer_category' => null,
        'service_category' => null,
        'hreflang_default_domain' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'language_id' => 'languageId',
        'customer_group_id' => 'customerGroupId',
        'currency_id' => 'currencyId',
        'payment_method_id' => 'paymentMethodId',
        'shipping_method_id' => 'shippingMethodId',
        'country_id' => 'countryId',
        'navigation_category_id' => 'navigationCategoryId',
        'navigation_category_version_id' => 'navigationCategoryVersionId',
        'navigation_category_depth' => 'navigationCategoryDepth',
        'footer_category_id' => 'footerCategoryId',
        'footer_category_version_id' => 'footerCategoryVersionId',
        'service_category_id' => 'serviceCategoryId',
        'service_category_version_id' => 'serviceCategoryVersionId',
        'mail_header_footer_id' => 'mailHeaderFooterId',
        'hreflang_default_domain_id' => 'hreflangDefaultDomainId',
        'name' => 'name',
        'short_name' => 'shortName',
        'tax_calculation_type' => 'taxCalculationType',
        'configuration' => 'configuration',
        'active' => 'active',
        'hreflang_active' => 'hreflangActive',
        'maintenance' => 'maintenance',
        'custom_fields' => 'customFields',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'translated' => 'translated',
        'language' => 'language',
        'currency' => 'currency',
        'payment_method' => 'paymentMethod',
        'shipping_method' => 'shippingMethod',
        'country' => 'country',
        'domains' => 'domains',
        'navigation_category' => 'navigationCategory',
        'footer_category' => 'footerCategory',
        'service_category' => 'serviceCategory',
        'hreflang_default_domain' => 'hreflangDefaultDomain'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'language_id' => 'setLanguageId',
        'customer_group_id' => 'setCustomerGroupId',
        'currency_id' => 'setCurrencyId',
        'payment_method_id' => 'setPaymentMethodId',
        'shipping_method_id' => 'setShippingMethodId',
        'country_id' => 'setCountryId',
        'navigation_category_id' => 'setNavigationCategoryId',
        'navigation_category_version_id' => 'setNavigationCategoryVersionId',
        'navigation_category_depth' => 'setNavigationCategoryDepth',
        'footer_category_id' => 'setFooterCategoryId',
        'footer_category_version_id' => 'setFooterCategoryVersionId',
        'service_category_id' => 'setServiceCategoryId',
        'service_category_version_id' => 'setServiceCategoryVersionId',
        'mail_header_footer_id' => 'setMailHeaderFooterId',
        'hreflang_default_domain_id' => 'setHreflangDefaultDomainId',
        'name' => 'setName',
        'short_name' => 'setShortName',
        'tax_calculation_type' => 'setTaxCalculationType',
        'configuration' => 'setConfiguration',
        'active' => 'setActive',
        'hreflang_active' => 'setHreflangActive',
        'maintenance' => 'setMaintenance',
        'custom_fields' => 'setCustomFields',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'translated' => 'setTranslated',
        'language' => 'setLanguage',
        'currency' => 'setCurrency',
        'payment_method' => 'setPaymentMethod',
        'shipping_method' => 'setShippingMethod',
        'country' => 'setCountry',
        'domains' => 'setDomains',
        'navigation_category' => 'setNavigationCategory',
        'footer_category' => 'setFooterCategory',
        'service_category' => 'setServiceCategory',
        'hreflang_default_domain' => 'setHreflangDefaultDomain'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'language_id' => 'getLanguageId',
        'customer_group_id' => 'getCustomerGroupId',
        'currency_id' => 'getCurrencyId',
        'payment_method_id' => 'getPaymentMethodId',
        'shipping_method_id' => 'getShippingMethodId',
        'country_id' => 'getCountryId',
        'navigation_category_id' => 'getNavigationCategoryId',
        'navigation_category_version_id' => 'getNavigationCategoryVersionId',
        'navigation_category_depth' => 'getNavigationCategoryDepth',
        'footer_category_id' => 'getFooterCategoryId',
        'footer_category_version_id' => 'getFooterCategoryVersionId',
        'service_category_id' => 'getServiceCategoryId',
        'service_category_version_id' => 'getServiceCategoryVersionId',
        'mail_header_footer_id' => 'getMailHeaderFooterId',
        'hreflang_default_domain_id' => 'getHreflangDefaultDomainId',
        'name' => 'getName',
        'short_name' => 'getShortName',
        'tax_calculation_type' => 'getTaxCalculationType',
        'configuration' => 'getConfiguration',
        'active' => 'getActive',
        'hreflang_active' => 'getHreflangActive',
        'maintenance' => 'getMaintenance',
        'custom_fields' => 'getCustomFields',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'translated' => 'getTranslated',
        'language' => 'getLanguage',
        'currency' => 'getCurrency',
        'payment_method' => 'getPaymentMethod',
        'shipping_method' => 'getShippingMethod',
        'country' => 'getCountry',
        'domains' => 'getDomains',
        'navigation_category' => 'getNavigationCategory',
        'footer_category' => 'getFooterCategory',
        'service_category' => 'getServiceCategory',
        'hreflang_default_domain' => 'getHreflangDefaultDomain'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['language_id'] = $data['language_id'] ?? null;
        $this->container['customer_group_id'] = $data['customer_group_id'] ?? null;
        $this->container['currency_id'] = $data['currency_id'] ?? null;
        $this->container['payment_method_id'] = $data['payment_method_id'] ?? null;
        $this->container['shipping_method_id'] = $data['shipping_method_id'] ?? null;
        $this->container['country_id'] = $data['country_id'] ?? null;
        $this->container['navigation_category_id'] = $data['navigation_category_id'] ?? null;
        $this->container['navigation_category_version_id'] = $data['navigation_category_version_id'] ?? null;
        $this->container['navigation_category_depth'] = $data['navigation_category_depth'] ?? null;
        $this->container['footer_category_id'] = $data['footer_category_id'] ?? null;
        $this->container['footer_category_version_id'] = $data['footer_category_version_id'] ?? null;
        $this->container['service_category_id'] = $data['service_category_id'] ?? null;
        $this->container['service_category_version_id'] = $data['service_category_version_id'] ?? null;
        $this->container['mail_header_footer_id'] = $data['mail_header_footer_id'] ?? null;
        $this->container['hreflang_default_domain_id'] = $data['hreflang_default_domain_id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['short_name'] = $data['short_name'] ?? null;
        $this->container['tax_calculation_type'] = $data['tax_calculation_type'] ?? null;
        $this->container['configuration'] = $data['configuration'] ?? null;
        $this->container['active'] = $data['active'] ?? null;
        $this->container['hreflang_active'] = $data['hreflang_active'] ?? null;
        $this->container['maintenance'] = $data['maintenance'] ?? null;
        $this->container['custom_fields'] = $data['custom_fields'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['translated'] = $data['translated'] ?? null;
        $this->container['language'] = $data['language'] ?? null;
        $this->container['currency'] = $data['currency'] ?? null;
        $this->container['payment_method'] = $data['payment_method'] ?? null;
        $this->container['shipping_method'] = $data['shipping_method'] ?? null;
        $this->container['country'] = $data['country'] ?? null;
        $this->container['domains'] = $data['domains'] ?? null;
        $this->container['navigation_category'] = $data['navigation_category'] ?? null;
        $this->container['footer_category'] = $data['footer_category'] ?? null;
        $this->container['service_category'] = $data['service_category'] ?? null;
        $this->container['hreflang_default_domain'] = $data['hreflang_default_domain'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['language_id'] === null) {
            $invalidProperties[] = "'language_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['language_id'])) {
            $invalidProperties[] = "invalid value for 'language_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['customer_group_id'] === null) {
            $invalidProperties[] = "'customer_group_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['customer_group_id'])) {
            $invalidProperties[] = "invalid value for 'customer_group_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['currency_id'] === null) {
            $invalidProperties[] = "'currency_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['currency_id'])) {
            $invalidProperties[] = "invalid value for 'currency_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['payment_method_id'] === null) {
            $invalidProperties[] = "'payment_method_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['payment_method_id'])) {
            $invalidProperties[] = "invalid value for 'payment_method_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['shipping_method_id'] === null) {
            $invalidProperties[] = "'shipping_method_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['shipping_method_id'])) {
            $invalidProperties[] = "invalid value for 'shipping_method_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['country_id'] === null) {
            $invalidProperties[] = "'country_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['country_id'])) {
            $invalidProperties[] = "invalid value for 'country_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['navigation_category_id'] === null) {
            $invalidProperties[] = "'navigation_category_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['navigation_category_id'])) {
            $invalidProperties[] = "invalid value for 'navigation_category_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['navigation_category_version_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['navigation_category_version_id'])) {
            $invalidProperties[] = "invalid value for 'navigation_category_version_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['footer_category_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['footer_category_id'])) {
            $invalidProperties[] = "invalid value for 'footer_category_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['footer_category_version_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['footer_category_version_id'])) {
            $invalidProperties[] = "invalid value for 'footer_category_version_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['service_category_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['service_category_id'])) {
            $invalidProperties[] = "invalid value for 'service_category_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['service_category_version_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['service_category_version_id'])) {
            $invalidProperties[] = "invalid value for 'service_category_version_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['mail_header_footer_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['mail_header_footer_id'])) {
            $invalidProperties[] = "invalid value for 'mail_header_footer_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['hreflang_default_domain_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['hreflang_default_domain_id'])) {
            $invalidProperties[] = "invalid value for 'hreflang_default_domain_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && (!preg_match("/^[0-9a-f]{32}$/", $id))) {
            throw new \InvalidArgumentException("invalid value for $id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets language_id
     *
     * @return string
     */
    public function getLanguageId()
    {
        return $this->container['language_id'];
    }

    /**
     * Sets language_id
     *
     * @param string $language_id language_id
     *
     * @return self
     */
    public function setLanguageId($language_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $language_id))) {
            throw new \InvalidArgumentException("invalid value for $language_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['language_id'] = $language_id;

        return $this;
    }

    /**
     * Gets customer_group_id
     *
     * @return string
     */
    public function getCustomerGroupId()
    {
        return $this->container['customer_group_id'];
    }

    /**
     * Sets customer_group_id
     *
     * @param string $customer_group_id customer_group_id
     *
     * @return self
     */
    public function setCustomerGroupId($customer_group_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $customer_group_id))) {
            throw new \InvalidArgumentException("invalid value for $customer_group_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['customer_group_id'] = $customer_group_id;

        return $this;
    }

    /**
     * Gets currency_id
     *
     * @return string
     */
    public function getCurrencyId()
    {
        return $this->container['currency_id'];
    }

    /**
     * Sets currency_id
     *
     * @param string $currency_id currency_id
     *
     * @return self
     */
    public function setCurrencyId($currency_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $currency_id))) {
            throw new \InvalidArgumentException("invalid value for $currency_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['currency_id'] = $currency_id;

        return $this;
    }

    /**
     * Gets payment_method_id
     *
     * @return string
     */
    public function getPaymentMethodId()
    {
        return $this->container['payment_method_id'];
    }

    /**
     * Sets payment_method_id
     *
     * @param string $payment_method_id payment_method_id
     *
     * @return self
     */
    public function setPaymentMethodId($payment_method_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $payment_method_id))) {
            throw new \InvalidArgumentException("invalid value for $payment_method_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['payment_method_id'] = $payment_method_id;

        return $this;
    }

    /**
     * Gets shipping_method_id
     *
     * @return string
     */
    public function getShippingMethodId()
    {
        return $this->container['shipping_method_id'];
    }

    /**
     * Sets shipping_method_id
     *
     * @param string $shipping_method_id shipping_method_id
     *
     * @return self
     */
    public function setShippingMethodId($shipping_method_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $shipping_method_id))) {
            throw new \InvalidArgumentException("invalid value for $shipping_method_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['shipping_method_id'] = $shipping_method_id;

        return $this;
    }

    /**
     * Gets country_id
     *
     * @return string
     */
    public function getCountryId()
    {
        return $this->container['country_id'];
    }

    /**
     * Sets country_id
     *
     * @param string $country_id country_id
     *
     * @return self
     */
    public function setCountryId($country_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $country_id))) {
            throw new \InvalidArgumentException("invalid value for $country_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['country_id'] = $country_id;

        return $this;
    }

    /**
     * Gets navigation_category_id
     *
     * @return string
     */
    public function getNavigationCategoryId()
    {
        return $this->container['navigation_category_id'];
    }

    /**
     * Sets navigation_category_id
     *
     * @param string $navigation_category_id navigation_category_id
     *
     * @return self
     */
    public function setNavigationCategoryId($navigation_category_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $navigation_category_id))) {
            throw new \InvalidArgumentException("invalid value for $navigation_category_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['navigation_category_id'] = $navigation_category_id;

        return $this;
    }

    /**
     * Gets navigation_category_version_id
     *
     * @return string|null
     */
    public function getNavigationCategoryVersionId()
    {
        return $this->container['navigation_category_version_id'];
    }

    /**
     * Sets navigation_category_version_id
     *
     * @param string|null $navigation_category_version_id navigation_category_version_id
     *
     * @return self
     */
    public function setNavigationCategoryVersionId($navigation_category_version_id)
    {

        if (!is_null($navigation_category_version_id) && (!preg_match("/^[0-9a-f]{32}$/", $navigation_category_version_id))) {
            throw new \InvalidArgumentException("invalid value for $navigation_category_version_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['navigation_category_version_id'] = $navigation_category_version_id;

        return $this;
    }

    /**
     * Gets navigation_category_depth
     *
     * @return int|null
     */
    public function getNavigationCategoryDepth()
    {
        return $this->container['navigation_category_depth'];
    }

    /**
     * Sets navigation_category_depth
     *
     * @param int|null $navigation_category_depth navigation_category_depth
     *
     * @return self
     */
    public function setNavigationCategoryDepth($navigation_category_depth)
    {
        $this->container['navigation_category_depth'] = $navigation_category_depth;

        return $this;
    }

    /**
     * Gets footer_category_id
     *
     * @return string|null
     */
    public function getFooterCategoryId()
    {
        return $this->container['footer_category_id'];
    }

    /**
     * Sets footer_category_id
     *
     * @param string|null $footer_category_id footer_category_id
     *
     * @return self
     */
    public function setFooterCategoryId($footer_category_id)
    {

        if (!is_null($footer_category_id) && (!preg_match("/^[0-9a-f]{32}$/", $footer_category_id))) {
            throw new \InvalidArgumentException("invalid value for $footer_category_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['footer_category_id'] = $footer_category_id;

        return $this;
    }

    /**
     * Gets footer_category_version_id
     *
     * @return string|null
     */
    public function getFooterCategoryVersionId()
    {
        return $this->container['footer_category_version_id'];
    }

    /**
     * Sets footer_category_version_id
     *
     * @param string|null $footer_category_version_id footer_category_version_id
     *
     * @return self
     */
    public function setFooterCategoryVersionId($footer_category_version_id)
    {

        if (!is_null($footer_category_version_id) && (!preg_match("/^[0-9a-f]{32}$/", $footer_category_version_id))) {
            throw new \InvalidArgumentException("invalid value for $footer_category_version_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['footer_category_version_id'] = $footer_category_version_id;

        return $this;
    }

    /**
     * Gets service_category_id
     *
     * @return string|null
     */
    public function getServiceCategoryId()
    {
        return $this->container['service_category_id'];
    }

    /**
     * Sets service_category_id
     *
     * @param string|null $service_category_id service_category_id
     *
     * @return self
     */
    public function setServiceCategoryId($service_category_id)
    {

        if (!is_null($service_category_id) && (!preg_match("/^[0-9a-f]{32}$/", $service_category_id))) {
            throw new \InvalidArgumentException("invalid value for $service_category_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['service_category_id'] = $service_category_id;

        return $this;
    }

    /**
     * Gets service_category_version_id
     *
     * @return string|null
     */
    public function getServiceCategoryVersionId()
    {
        return $this->container['service_category_version_id'];
    }

    /**
     * Sets service_category_version_id
     *
     * @param string|null $service_category_version_id service_category_version_id
     *
     * @return self
     */
    public function setServiceCategoryVersionId($service_category_version_id)
    {

        if (!is_null($service_category_version_id) && (!preg_match("/^[0-9a-f]{32}$/", $service_category_version_id))) {
            throw new \InvalidArgumentException("invalid value for $service_category_version_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['service_category_version_id'] = $service_category_version_id;

        return $this;
    }

    /**
     * Gets mail_header_footer_id
     *
     * @return string|null
     */
    public function getMailHeaderFooterId()
    {
        return $this->container['mail_header_footer_id'];
    }

    /**
     * Sets mail_header_footer_id
     *
     * @param string|null $mail_header_footer_id mail_header_footer_id
     *
     * @return self
     */
    public function setMailHeaderFooterId($mail_header_footer_id)
    {

        if (!is_null($mail_header_footer_id) && (!preg_match("/^[0-9a-f]{32}$/", $mail_header_footer_id))) {
            throw new \InvalidArgumentException("invalid value for $mail_header_footer_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['mail_header_footer_id'] = $mail_header_footer_id;

        return $this;
    }

    /**
     * Gets hreflang_default_domain_id
     *
     * @return string|null
     */
    public function getHreflangDefaultDomainId()
    {
        return $this->container['hreflang_default_domain_id'];
    }

    /**
     * Sets hreflang_default_domain_id
     *
     * @param string|null $hreflang_default_domain_id hreflang_default_domain_id
     *
     * @return self
     */
    public function setHreflangDefaultDomainId($hreflang_default_domain_id)
    {

        if (!is_null($hreflang_default_domain_id) && (!preg_match("/^[0-9a-f]{32}$/", $hreflang_default_domain_id))) {
            throw new \InvalidArgumentException("invalid value for $hreflang_default_domain_id when calling SalesChannel., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['hreflang_default_domain_id'] = $hreflang_default_domain_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets short_name
     *
     * @return string|null
     */
    public function getShortName()
    {
        return $this->container['short_name'];
    }

    /**
     * Sets short_name
     *
     * @param string|null $short_name short_name
     *
     * @return self
     */
    public function setShortName($short_name)
    {
        $this->container['short_name'] = $short_name;

        return $this;
    }

    /**
     * Gets tax_calculation_type
     *
     * @return string|null
     */
    public function getTaxCalculationType()
    {
        return $this->container['tax_calculation_type'];
    }

    /**
     * Sets tax_calculation_type
     *
     * @param string|null $tax_calculation_type tax_calculation_type
     *
     * @return self
     */
    public function setTaxCalculationType($tax_calculation_type)
    {
        $this->container['tax_calculation_type'] = $tax_calculation_type;

        return $this;
    }

    /**
     * Gets configuration
     *
     * @return object|null
     */
    public function getConfiguration()
    {
        return $this->container['configuration'];
    }

    /**
     * Sets configuration
     *
     * @param object|null $configuration configuration
     *
     * @return self
     */
    public function setConfiguration($configuration)
    {
        $this->container['configuration'] = $configuration;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active active
     *
     * @return self
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets hreflang_active
     *
     * @return bool|null
     */
    public function getHreflangActive()
    {
        return $this->container['hreflang_active'];
    }

    /**
     * Sets hreflang_active
     *
     * @param bool|null $hreflang_active hreflang_active
     *
     * @return self
     */
    public function setHreflangActive($hreflang_active)
    {
        $this->container['hreflang_active'] = $hreflang_active;

        return $this;
    }

    /**
     * Gets maintenance
     *
     * @return bool|null
     */
    public function getMaintenance()
    {
        return $this->container['maintenance'];
    }

    /**
     * Sets maintenance
     *
     * @param bool|null $maintenance maintenance
     *
     * @return self
     */
    public function setMaintenance($maintenance)
    {
        $this->container['maintenance'] = $maintenance;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets translated
     *
     * @return object|null
     */
    public function getTranslated()
    {
        return $this->container['translated'];
    }

    /**
     * Sets translated
     *
     * @param object|null $translated translated
     *
     * @return self
     */
    public function setTranslated($translated)
    {
        $this->container['translated'] = $translated;

        return $this;
    }

    /**
     * Gets language
     *
     * @return \ServeXS\Shopware\v6\Store\Model\Language|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param \ServeXS\Shopware\v6\Store\Model\Language|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \ServeXS\Shopware\v6\Store\Model\Currency|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \ServeXS\Shopware\v6\Store\Model\Currency|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return \ServeXS\Shopware\v6\Store\Model\PaymentMethod|null
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param \ServeXS\Shopware\v6\Store\Model\PaymentMethod|null $payment_method payment_method
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets shipping_method
     *
     * @return \ServeXS\Shopware\v6\Store\Model\ShippingMethod|null
     */
    public function getShippingMethod()
    {
        return $this->container['shipping_method'];
    }

    /**
     * Sets shipping_method
     *
     * @param \ServeXS\Shopware\v6\Store\Model\ShippingMethod|null $shipping_method shipping_method
     *
     * @return self
     */
    public function setShippingMethod($shipping_method)
    {
        $this->container['shipping_method'] = $shipping_method;

        return $this;
    }

    /**
     * Gets country
     *
     * @return \ServeXS\Shopware\v6\Store\Model\Country|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param \ServeXS\Shopware\v6\Store\Model\Country|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return \ServeXS\Shopware\v6\Store\Model\SalesChannelDomain|null
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param \ServeXS\Shopware\v6\Store\Model\SalesChannelDomain|null $domains domains
     *
     * @return self
     */
    public function setDomains($domains)
    {
        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets navigation_category
     *
     * @return \ServeXS\Shopware\v6\Store\Model\Category|null
     */
    public function getNavigationCategory()
    {
        return $this->container['navigation_category'];
    }

    /**
     * Sets navigation_category
     *
     * @param \ServeXS\Shopware\v6\Store\Model\Category|null $navigation_category navigation_category
     *
     * @return self
     */
    public function setNavigationCategory($navigation_category)
    {
        $this->container['navigation_category'] = $navigation_category;

        return $this;
    }

    /**
     * Gets footer_category
     *
     * @return \ServeXS\Shopware\v6\Store\Model\Category|null
     */
    public function getFooterCategory()
    {
        return $this->container['footer_category'];
    }

    /**
     * Sets footer_category
     *
     * @param \ServeXS\Shopware\v6\Store\Model\Category|null $footer_category footer_category
     *
     * @return self
     */
    public function setFooterCategory($footer_category)
    {
        $this->container['footer_category'] = $footer_category;

        return $this;
    }

    /**
     * Gets service_category
     *
     * @return \ServeXS\Shopware\v6\Store\Model\Category|null
     */
    public function getServiceCategory()
    {
        return $this->container['service_category'];
    }

    /**
     * Sets service_category
     *
     * @param \ServeXS\Shopware\v6\Store\Model\Category|null $service_category service_category
     *
     * @return self
     */
    public function setServiceCategory($service_category)
    {
        $this->container['service_category'] = $service_category;

        return $this;
    }

    /**
     * Gets hreflang_default_domain
     *
     * @return \ServeXS\Shopware\v6\Store\Model\SalesChannelDomain|null
     */
    public function getHreflangDefaultDomain()
    {
        return $this->container['hreflang_default_domain'];
    }

    /**
     * Sets hreflang_default_domain
     *
     * @param \ServeXS\Shopware\v6\Store\Model\SalesChannelDomain|null $hreflang_default_domain hreflang_default_domain
     *
     * @return self
     */
    public function setHreflangDefaultDomain($hreflang_default_domain)
    {
        $this->container['hreflang_default_domain'] = $hreflang_default_domain;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


