<?php
/**
 * AddressApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ServeXS\Shopware\v6\Store\Test\Api;

use \ServeXS\Shopware\v6\Store\Configuration;
use \ServeXS\Shopware\v6\Store\ApiException;
use \ServeXS\Shopware\v6\Store\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCustomerAddress
     *
     * Create a new address for a customer.
     *
     */
    public function testCreateCustomerAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for defaultBillingAddress
     *
     * Change a customer's default billing address.
     *
     */
    public function testDefaultBillingAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for defaultShippingAddress
     *
     * Change a customer's default shipping address.
     *
     */
    public function testDefaultShippingAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCustomerAddress
     *
     * Delete an address of a customer.
     *
     */
    public function testDeleteCustomerAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAddress
     *
     * Fetch addresses of a customer.
     *
     */
    public function testListAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomerAddress
     *
     * Modify an address of a customer.
     *
     */
    public function testUpdateCustomerAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
