<?php
/**
 * ProductApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ServeXS\Shopware\v6\Store\Test\Api;

use \ServeXS\Shopware\v6\Store\Configuration;
use \ServeXS\Shopware\v6\Store\ApiException;
use \ServeXS\Shopware\v6\Store\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for readProduct
     *
     * Fetch a list of products.
     *
     */
    public function testReadProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readProductCrossSellings
     *
     * Fetch cross-selling groups of a product.
     *
     */
    public function testReadProductCrossSellings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readProductDetail
     *
     * Fetch a single product.
     *
     */
    public function testReadProductDetail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readProductExport
     *
     * Export product export.
     *
     */
    public function testReadProductExport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readProductListing
     *
     * Fetch a product listing by category.
     *
     */
    public function testReadProductListing()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readProductReviews
     *
     * Fetch product reviews.
     *
     */
    public function testReadProductReviews()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveProductReview
     *
     * Save a product review.
     *
     */
    public function testSaveProductReview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchPage
     *
     * Search for products.
     *
     */
    public function testSearchPage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchSuggest
     *
     * Search for products (suggest).
     *
     */
    public function testSearchSuggest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
