<?php
/**
 * ProfileApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ServeXS\Shopware\v6\Store\Test\Api;

use \ServeXS\Shopware\v6\Store\Configuration;
use \ServeXS\Shopware\v6\Store\ApiException;
use \ServeXS\Shopware\v6\Store\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProfileApiTest Class Doc Comment
 *
 * @category Class
 * @package  ServeXS\Shopware\v6\Store
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changeEmail
     *
     * Change the customer's email address.
     *
     */
    public function testChangeEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for changePassword
     *
     * Change the customer's password.
     *
     */
    public function testChangePassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for changePaymentMethod
     *
     * Change the customer's default payment method.
     *
     */
    public function testChangePaymentMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for changeProfile
     *
     * Change the customer's information.
     *
     */
    public function testChangeProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCustomer
     *
     * Delete the customer's profile.
     *
     */
    public function testDeleteCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readCustomer
     *
     * Get information about current customer.
     *
     */
    public function testReadCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recoveryPassword
     *
     * Reset a password with recovery credentials.
     *
     */
    public function testRecoveryPassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendRecoveryMail
     *
     * Send a password recovery mail.
     *
     */
    public function testSendRecoveryMail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
